# Generated by Django 3.0 on 2020-06-07 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=512, unique=True)),
                ('timestap', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
