# Generated by Django 3.0 on 2020-06-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
