# Generated by Django 3.0 on 2020-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_auto_20200608_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=600),
        ),
    ]
