# Generated by Django 3.0 on 2020-06-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20200608_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='name',
        ),
    ]
